### PR TITLE
use absolute URI for context

### PR DESCRIPTION
**Pull request by angelo-v**

### CODE REVIEW

**Comment by alien-mcl** [comment]
Is there any specific reason to use absolute URLs for context?

**Comment by tpluscode** [comment]
Relative context makes a document unusable outside of http request context because you do not know the base uri. Such as when you do 'save as' in the browser

**Comment by alien-mcl** [comment]
I know that. Just curiosity - in what case this document will be used outside HTTP request context?
I mean that normally, this would be server-side generated and once obtained it's up to the client on how to handle the payload.

**Comment by tpluscode** [comment]
> Just curiosity - in what case this document will be used outside HTTP request context?

Well, precisely when the JSON-LD body is taken from the browser or piped from curl to a file for future processing (think an API crawler saving representations for async processing)

**Comment by tpluscode** [comment]
That said I have to oppose this PR.

I mentioned this context thing in the cookbook and I think it's worth suggesting to serve absolute context. BUT, it requires some kind of config and dynamic server to use the right base depending on the environment (location, development, production).

Neither which we have using just some static files.

**Comment by angelo-v** [comment]
The cookbook examples should match the API output, this is why I changed it here as well. Additionally jsonld.js had indeed problems to process the JSON-LD because of the relative context URI, I think it prependet the browser URI as a base and not the API URI.

**Comment by tpluscode** [comment]
> The cookbook examples should match the API output, this is why I changed it here as well

My point was that we won't be able to easily deploy branches now. Or well, we will but they will be pointing to potentially incorrect context.

> I think it prependet the browser URI as a base and not the API URI.

Yes, I had that same problem myself. You have to explicitly pass the `baseIRI` option to JSON-LD parser. Lib like `@rdfjs/fetch-lite` should do it but otherwise every implementor must take care of that

**Comment by alien-mcl** [comment]
>My point was that we won't be able to easily deploy branches now.

Thank you - that was my point. I was somehow uncomfortable with only me seeing deployment issues due to fixed urls.

>Yes, I had that same problem myself. You have to explicitly pass the baseIRI option to JSON-LD parser.

Exactly. Example: Heracles.ts does it when processing received payloads by using baseIRI from the requested URL.

**Comment by angelo-v** [comment]
I am aware of the deployment problem, but thought it would be less of a problem than not beeing able to process the data at all.

> You have to explicitly pass the `baseIRI` option to JSON-LD parser.

I was not aware of that possibility. So for the static files let's keep the relative URI and for a real implementation let's make the base URI configurable

**Pull request closed without merging**
